services:
  reservation:
    build: 
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm start:debug reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - reservation_node_modules:/usr/src/app/node_modules
  mongo: 
    image: mongo
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - auth_node_modules:/usr/src/app/node_modules
      - auth_app_node_modules:/usr/src/app/apps/auth/node_modules
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app
      - payments_node_modules:/usr/src/app/node_modules
      - payments_app_node_modules:/usr/src/app/apps/payments/node_modules
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
      - notifications_node_modules:/usr/src/app/node_modules
      - notifications_app_node_modules:/usr/src/app/apps/notifications/node_modules
volumes:
  reservation_node_modules:
  auth_node_modules:
  auth_app_node_modules:
  payments_node_modules:
  payments_app_node_modules:
  notifications_node_modules:
  notifications_app_node_modules:
   
    